---
# Ansible playbook for an AWX server.
# This playbook generates self signer SSL certificate for AWX
# Requires community.crypto from Ansible Galaxy
#   ansible-galaxy collection install community.crypto

- name: Generate slef signed SSL certificate for AWX
  hosts: awx
  gather_facts: yes
  become: yes

  tasks:
    - name: Is this Debian?
      fail: msg="Debian only playbook"
      when:
        - ansible_facts['distribution'] != "Debian"

    - name: Generate the private key file to sign the CSR
      community.crypto.openssl_privatekey:
        path: /tmp/awx.local.pem
        passphrase: "password"
        cipher: auto

    - name: Generate the CSR file signed with the private key
      community.crypto.openssl_csr:
        path: /tmp/awx.local.csr
        privatekey_path: /tmp/awx.local.pem
        privatekey_passphrase: "password"
        common_name: awx.local

    - name: Sign the CSR file as a CA to turn it into a certificate
      community.crypto.openssl_certificate:
        path: /tmp/awx.local.crt
        privatekey_path: /tmp/awx.local.pem
        privatekey_passphrase: "password"
        csr_path: /tmp/awx.local.csr
        provider: selfsigned

    #- name: Convert the signed certificate into a PKCS12 file with the attached private key
    #  community.crypto.openssl_pkcs12:
    #    action: export
    #    path: /tmp/awx.local.pfx
    #    name: "awx.local"
    #    privatekey_path: /tmp/awx.local.pem
    #    privatekey_passphrase: "password"
    #    passphrase: password
    #    certificate_path: /tmp/awx.local.crt
    #    state: present
