---
# Ansible playbook for an AWX minions

- name: Setup Tool VM
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Is this Debian?
      fail: msg="Debian only playbook"
      when:
        - ansible_facts['distribution'] != "Debian"

      - name: Install Xfce GUI
        package:
          name: xfce-desktop
          state: present
