---
# Ansible playbook for an AWX server.
# This playbooks install all needed components needed to run AWX.
# configure_awx.yml is used to configure AWS and add minions.

- name: Build AWX VM
  hosts: awx
  gather_facts: yes
  become: yes

  tasks:
    - name: Is this Debian?
      fail: msg="Debian only playbook"
      when:
        - ansible_facts['distribution'] != "Debian"

    - name: Add an APT key for Ansible repository
      ansible.builtin.apt_key:
        keyserver: keyserver.ubuntu.com
        id: 93C4A3FD7BB9C367

    - name: Add Ansible repository
      ansible.builtin.apt_repository:
        repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
        state: present
        update_cache: yes

    - name: Install Ansible
      package:
        name: ansible
        state: present

    - name: Install required packages for Docker
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker's official APT key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_key
      ignore_errors: true

    #- name: Add Docker apt key if failed
    #  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
    #  args:
    #    warn: no
    #  when: add_key|failed

    - name: Add Docker stable repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
        state: present
        update_cache: yes

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Install required packaged for Ansible AWX
      package:
        name:
          - nodejs
          - npm
          - git
        state: present

    - name: Install NPM as global
      community.general.npm:
        name: npm
        global: yes
        state: present

    - name: Install Python for Docker
      package:
        name:
          - python3-pip
          - pwgen
          - python3-docker
        state: present

    - name: Install Python modules for Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Clone AWX 17.0.1 repository
      git:
          repo: 'https://github.com/ansible/awx.git'
          dest: /tmp/awx
          force: yes
          version: "17.0.1"

    - name: Copy customized inventory file for AWX
      ansible.builtin.copy:
        src: inventory_awx.txt
        dest: /tmp/awx/installer/inventory
        owner: root
        group: root
        mode: '0754'

    - name: Generate the private key file to sign the CSR
      community.crypto.openssl_privatekey:
        path: /root/awx.local.pem
        passphrase: "password"
        cipher: auto

    - name: Generate the CSR file signed with the private key
      community.crypto.openssl_csr:
        path: /root/awx.local.csr
        privatekey_path: /root/awx.local.pem
        privatekey_passphrase: "password"
        common_name: awx.local

    - name: Sign the CSR file as a CA to turn it into a certificate
      community.crypto.x509_certificate:
        path: /root/awx.local.crt
        privatekey_path: /root/awx.local.pem
        privatekey_passphrase: "password"
        csr_path: /root/awx.local.csr
        provider: selfsigned

    - name: Run the AWX installation playbook.
      command: "ansible-playbook -i inventory install.yml -e postgres_data_dir=/var/lib/pgdocker"
      args:
        chdir: "/tmp/awx/installer"

    - name: Install AWX CLI
      pip:
          name: awxkit
          state: present

    - name: Update /etc/host
      blockinfile:
        path: /etc/hosts
        insertafter: EOF
        marker: "# {mark} minions to manage"
        block: |
          192.168.6.66 minion1.local minion1
          192.168.6.67 minion2.local minion2
          192.168.6.68 tool.local tool
