---
# Ansible playbook for an AWX minions

- name: Setup Minion VM
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Is this Debian?
      fail: msg="Debian only playbook"
      when:
        - ansible_facts['distribution'] != "Debian"

    - name: Add minion1 and awx to /etc/hosts
      blockinfile:
        path: /etc/hosts
        insertafter: EOF
        marker: "# {mark} other minions"
        block: |
          192.168.6.66 minion1.local minion1
          192.168.6.65 awx.local awx
      when:
        - ansible_facts['nodename'] == "minion2"

    - name: Add minion2 and axw to /etc/hosts
      blockinfile:
        path: /etc/hosts
        insertafter: EOF
        marker: "# {mark} other minions"
        block: |
          192.168.6.65 awx.local awx
          192.168.6.67 minion2.local minion2
      when:
        - ansible_facts['nodename'] == "minion1"
